import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const jsPath = resolve(root, 'node_modules/rrweb/dist/rrweb.umd.cjs');
const cssPath = resolve(root, 'node_modules/rrweb/dist/style.css');

const js = readFileSync(jsPath, 'utf-8');
const css = readFileSync(cssPath, 'utf-8');

const output = `// AUTO-GENERATED by scripts/bundle-rrweb.ts — do not edit manually
export const RRWEB_JS = ${JSON.stringify(js)};
export const RRWEB_CSS = ${JSON.stringify(css)};
`;

const outPath = resolve(root, 'src/templates/rrweb-bundle.ts');
writeFileSync(outPath, output, 'utf-8');

console.log(`Wrote rrweb bundle to ${outPath}`);
console.log(`  JS: ${(js.length / 1024).toFixed(1)} KB`);
console.log(`  CSS: ${(css.length / 1024).toFixed(1)} KB`);
